pref_index:
    path:     /
    defaults: { _controller: "HelixProjetBundle:preferences:index" }
    methods:  GET

pref_show:
    path:     /{id}/show
    defaults: { _controller: "HelixProjetBundle:preferences:show" }
    methods:  GET

pref_new:
    path:     /new
    defaults: { _controller: "HelixProjetBundle:preferences:new" }
    methods:  [GET, POST]

pref_edit:
    path:     /{id}/edit
    defaults: { _controller: "HelixProjetBundle:preferences:edit" }
    methods:  [GET, POST]

pref_delete:
    path:     /{id}/delete
    defaults: { _controller: "HelixProjetBundle:preferences:delete" }
    methods:  DELETE
