helix_projet_dossier:
    resource: "@HelixProjetBundle/Resources/config/routing/dossier.yml"
    prefix:   /dossier

helix_projet_pack:
    resource: "@HelixProjetBundle/Resources/config/routing/pack.yml"
    prefix:   /pack


mesdossiers:
    path:     /myprojects
    defaults: { _controller: HelixProjetBundle:Dossier:userdossier }

testpack:
    path:     /newpack
    defaults: { _controller: HelixProjetBundle:Default:new }

