helix_user_user:
    resource: "@HelixUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

registrationSponsor:
    resource: "@HelixUserBundle/Resources/config/routing/user.yml"
    prefix:   /user