index:
    path:     /
    defaults: { _controller: HelixFrontBundle:Main:index }


allsponsors:
    path:     /allsponsors
    defaults: { _controller: HelixFrontBundle:Main:allsponsor }

aboutus:
    path:     /aboutus
    defaults: { _controller: HelixFrontBundle:Main:about }

erreuraddprojet:
    path:     /ajoutDossier
    defaults: { _controller: HelixFrontBundle:Main:erreuraddproject }

contact:
    path:     /contact
    defaults: { _controller: HelixFrontBundle:Contact:contact }