helix_blog_blog:
    resource: "@HelixBlogBundle/Resources/config/routing/blog.yml"
    prefix:   /blog

allarticles:
    path:     /blogs
    defaults: { _controller: HelixBlogBundle:CrudBlog:index }

detailarticle:
    path:     /{id}/blog-detail
    defaults: { _controller: HelixBlogBundle:Blog:show }