helix_backoffice_homepage:
    path:     /
    defaults: { _controller: HelixBackofficeBundle:Default:index }

dashboard:
    path:     /dashboard
    defaults: { _controller: HelixBackofficeBundle:Main:index }