blog_index:
    path:     /
    defaults: { _controller: "HelixBlogBundle:Blog:index" }
    methods:  GET

blog_show:
    path:     /{id}/show
    defaults: { _controller: "HelixBlogBundle:Blog:show" }
    methods:  GET

blog_new:
    path:     /new
    defaults: { _controller: "HelixBlogBundle:Blog:new" }
    methods:  [GET, POST]

blog_edit:
    path:     /{id}/edit
    defaults: { _controller: "HelixBlogBundle:Blog:edit" }
    methods:  [GET, POST]

blog_delete:
    path:     /{id}/delete
    defaults: { _controller: "HelixBlogBundle:Blog:delete" }
    methods:  DELETE

blog_deletelink:
    path:     /{id}/deleteblog
    defaults: { _controller: "HelixBlogBundle:Blog:deletelink" }
