user_index:
    path:     /
    defaults: { _controller: "HelixUserBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "HelixUserBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "HelixUserBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "HelixUserBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "HelixUserBundle:User:delete" }
    methods:  DELETE

registration_sponsor:
    path:     /newSponsor
    defaults: { _controller: "HelixUserBundle:User:newSponsor" }
    methods:  [GET, POST]

allSponsors:
    path:     /allSponsors
    defaults: { _controller: "HelixUserBundle:User:allsponsors" }
    methods:  [GET, POST]

ban:
    path:     /banned
    defaults: { _controller: "HelixUserBundle:User:blockedUser" }
    methods:  [GET, POST]

ban_user:
    path:     /{id}/ban
    defaults: { _controller: "HelixUserBundle:User:bannir" }
    methods:  [GET, POST]

toGold:
    path:     /{id}/togold
    defaults: { _controller: "HelixUserBundle:User:toGold" }
    methods:  [GET, POST]

toPremium:
    path:     /{id}/topremium
    defaults: { _controller: "HelixUserBundle:User:toPremium" }
    methods:  [GET, POST]

unlock:
    path:     /{id}/unlock
    defaults: { _controller: "HelixUserBundle:User:unlockUser" }
    methods:  [GET, POST]